from flask import current_app

from breadbox_client import Client
from breadbox_facade import BBClient
from depmap.access_control import get_current_user_for_access_control
from typing import Optional


class BreadboxClientExtension:
    """
    Contains an instance of the breadbox_facade.BBClient, which the uses autogenerated 
    breadbox_client module to maintain a connection to the breadbox database.  
    """

    def __init__(self, app=None) -> None:
        if app is not None:
            self.init_app(app)

    def init_app(self, app):
        self.app = app

    def get_client_for_user(self, user: Optional[str]):
        base_url = current_app.config["BREADBOX_PROXY_TARGET"]
        if user is None:
            user = get_current_user_for_access_control()
        client = BBClient(base_url=base_url, user=user)
        return client

    @property
    def client(self) -> BBClient:
        return self.get_client_for_user(None)
