name: "publish-breadbox-client"
description: "Publishes breadbox client to google artifact service"
inputs:
  credentials_json:
    description: |-
      the "credentials_json" (which should be stored as a secret).
    required: false
runs:
  using: "composite"
  steps:
    - name: "Authenticate to Google Cloud"
      uses: google-github-actions/auth@v2
      with:
        # See instructions here: https://github.com/google-github-actions/auth?tab=readme-ov-file#service-account-key-json
        credentials_json: ${{ env.INPUT_CREDENTIALS_JSON }}

    - name: "Set up authentication for publishing breadbox client"
      working-directory: "./breadbox-client"
      run: |
        find ./breadbox_client 
        poetry self add keyrings.google-artifactregistry-auth
        poetry config repositories.public-python https://us-central1-python.pkg.dev/cds-artifacts/public-python/
      shell: bash

    - name: "Publish new breadbox client version to Artifact Registry"
      working-directory: "./breadbox-client"
      run: |
        poetry publish --build --repository public-python
      shell: bash
