# A re-usable github action which does the initial checkout and sets up poetry with caching for breadbox
name: "prepare-breadbox"
description: "Checks out and prepares poetry (with caching)"
runs:
  using: "composite"
  steps:
    - name: "Compute poetry cache dir"
      id: "poetry-cachedir"
      run: 'echo POETRY_CACHEDIR="$HOME/.cache/pypoetry" >> "$GITHUB_OUTPUT"'
      shell: bash

    - name: "Install and configure Poetry"
      uses: snok/install-poetry@v1
      with:
        version: 2.2
        virtualenvs-create: true

    - name: "Set up poetry cache"
      uses: actions/cache@v3
      id: cached-poetry-dependencies
      with:
        path: "${{ steps.poetry-cachedir.outputs.POETRY_CACHEDIR }}"
        key: "breadbox-venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('breadbox*/**/poetry.lock') }}"
#    - name: "peek at poetry cachedir (for debugging)"
#      run: "ls -l ${{ steps.poetry-cachedir.outputs.POETRY_CACHEDIR }}/* || true"
#      shell: bash
