# A re-usable github action which generates the breadbox client
name: "generate-breadbox-client"
description: "Auto-generate the breadbox client"
# TODO: determine if I need to set inputs or outputs
runs:
  steps:
    - uses: actions/checkout@v2
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install breadbox python dependencies
      working-directory: ./breadbox
      run: poetry install
      shell: bash
    - name: Export the breadbox API spec
      working-directory: ./breadbox
      run: |
        poetry run ./bb export-api-spec ../breadbox-client/latest-breadbox-api.json
      shell: bash
    - name: Generate the breadbox client
      run: |
        pip install openapi-python-client==0.21.1
        openapi-python-client generate --meta=none --output-path breadbox-client/breadbox_client --path breadbox-client/latest-breadbox-api.json --overwrite
      shell: bash
