import React, { useCallback, useState } from "react";
import styles from "src/dataPage/styles/DataPage.scss";
import ExtendedPlotType from "src/plot/models/ExtendedPlotType";
import DataAvailabilityPlot from "./DataAvailabilityPlot";
import { Button } from "react-bootstrap";
import DataStructureSection from "./DataStructureSection";
import LearnAboutDepMapSection from "./LearnAboutDepMapSection";
import HowDoICiteSection from "./HowDoICiteSection";
import { allDataTabHref, currentReleaseTabHref, de2PageHref } from "./utils";
import { DataAvailability } from "../models/types";
import MapSection from "./MapSection";

interface OverviewPanelProps {
  allDataAvail: DataAvailability;
  releaseNotesUrl: string | null;
  forumUrl: string | null;
  currentReleaseCitation: string | null;
}

function OverviewPanel(props: OverviewPanelProps) {
  const {
    allDataAvail,
    releaseNotesUrl,
    forumUrl,
    currentReleaseCitation,
  } = props;

  const [plotElement, setPlotElement] = useState<ExtendedPlotType | null>(null);
  const [
    dataStructureAccordionIsOpen,
    setDataStructureAccordionIsOpen,
  ] = useState<boolean>(false);

  // Hack to make the accordion isOpen state update on file search and exit. This is necessary due to
  // a problematic Accordion.tsx component that will eventually be replace. This component is problematic
  // because it's trying to be controlled (isOpen prop controls its state) and uncontrolled at the same
  // time (has its own isOpen state that it toggles internally without notifying its parent).
  const [keySuffix, setKeySuffix] = useState(0);
  const forceUpdate = () => setKeySuffix((n) => n + 1);

  // Support linking directly to citation section from other pages.
  const [citationSectionIsOpen, setCitationSectionIsOpen] = useState<boolean>(
    false
  );
  const [citationSectionKeySuffix, setCitationSectionKeySuffix] = useState(0);
  const forceCitationSectionUpdate = () =>
    setCitationSectionKeySuffix((n) => n + 1);
  const scroll = useCallback(() => {
    if (window.location.hash === "#how-to-cite" && document) {
      const target = window.location.hash;
      const element = document.querySelector(target)!;

      setTimeout(() => {
        window.scrollTo({
          top: element.getBoundingClientRect().top,
          behavior: "smooth",
        });
      }, 0);
      setCitationSectionIsOpen(true);
      forceCitationSectionUpdate();
    }
  }, []);

  return (
    <div className={styles.OverviewPanel}>
      <div className={styles.overview}>
        <div className={styles.overviewColumnLeft}>
          <div className={styles.overColumnHeader}>Overview</div>
          <div className={styles.overviewParagraphBold}>
            The DepMap project, building off of the original Cancer Cell Line
            Encyclopedia (CCLE) project, generates data and tools that can be
            used and shared by researchers. New DepMap data is released twice a
            year, in May and November.
          </div>
          <div className={styles.overviewParagraphBold}>
            DepMap has an ever-evolving data structure that allows for
            flexibility in incorporating and analyzing new types of data. To
            learn more about our data structure, read{" "}
            <a
              href={"#data-structure"}
              className={styles.dataPageLink}
              onClick={() => {
                setDataStructureAccordionIsOpen(true);
                forceUpdate();
              }}
            >
              &quot;How is DepMap data structured?&quot;
            </a>{" "}
            below.{" "}
          </div>
          <div className={styles.overviewParagraphBold2}>
            DepMap also hosts datasets that are generated with or provided by
            collaborators and other institutions. These datasets may or may not
            be continuously updated, but are available for the community to use
            through the DepMap Portal.
          </div>
          <div className={styles.overColumnHeader}>Release Datasets</div>
          <div className={styles.overviewParagraph}>
            The DepMap Release dataset is continuously growing as new data are
            generated by DepMap. Data may be analyzed and visualized using our
            portal tools, including{" "}
            <a
              className={styles.dataPageLink}
              href={de2PageHref}
              target="_blank"
              rel="noreferrer"
            >
              Data Explorer
            </a>
            . To learn more about our releases, visit the Current Release page.
          </div>
          <Button className={styles.readmeButton} href={currentReleaseTabHref}>
            View Current Release
          </Button>
          <div className={styles.overColumnHeader2}>Collaborative Datasets</div>
          <div className={styles.overviewParagraph}>
            The DepMap portal hosts datasets generated by collaborators for ease
            of use. Collaborator datasets are not maintained by DepMap, but may
            be available to use in some portal tools. Collaborator datasets
            generally have associated publications; check the dropdown for the
            dataset for more information, including methods. All collaborator
            datasets are harmonized by DepMap and available for download.
          </div>
          <Button className={styles.readmeButton} href={allDataTabHref}>
            View All Datasets
          </Button>
        </div>
        <div className={styles.overviewColumnRight}>
          <div className={styles.plotHeader}>
            Data sources used in the DepMap portal
          </div>
          <div className={styles.plotSubHeader}>
            Data in the DepMap portal is aggregated from many sources, including
            both DepMap Release data and collaborator datasets. This figure
            provides an overview of how many cell lines can be found in each
            data source.
          </div>
          <DataAvailabilityPlot
            currentReleaseDataAvil={allDataAvail}
            handleSetPlotElement={(element: ExtendedPlotType | null) => {
              setPlotElement(element);
            }}
            plotElement={plotElement}
          />
          {plotElement && (
            <div className={styles.plotFooter}>
              *These datasets are growing as part of the DepMap Release dataset.
            </div>
          )}
        </div>
      </div>
      <div className={styles.collapsibleSection}>
        <DataStructureSection
          dataStructureAccordionIsOpen={dataStructureAccordionIsOpen}
          keySuffix={keySuffix}
        />
      </div>
      <div className={styles.collapsibleSection2}>
        <MapSection />
      </div>
      <div className={styles.collapsibleSection2}>
        <LearnAboutDepMapSection
          releaseNotesUrl={releaseNotesUrl}
          forumUrl={forumUrl}
        />
      </div>
      <div className={styles.collapsibleSection3}>
        <HowDoICiteSection
          sectionIsOpen={citationSectionIsOpen}
          citationSectionKeySuffix={citationSectionKeySuffix}
          citation={currentReleaseCitation}
          scroll={scroll}
        />
      </div>
    </div>
  );
}

export default OverviewPanel;
