"""Add list_strings as matrix value type

Revision ID: 020788c82611
Revises: e593fefbe9fc
Create Date: 2025-03-13 14:42:21.461226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "020788c82611"
down_revision = "e593fefbe9fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("matrix_dataset", schema=None) as batch_op:
        batch_op.alter_column(
            "value_type",
            existing_type=sa.VARCHAR(length=11),
            type_=sa.Enum(
                "continuous", "categorical", "list_strings", name="valuetype"
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("matrix_dataset", schema=None) as batch_op:
        batch_op.alter_column(
            "value_type",
            existing_type=sa.Enum(
                "continuous", "categorical", "list_strings", name="valuetype"
            ),
            type_=sa.VARCHAR(length=11),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
