"""add cms posts and menu tables

Revision ID: 0c0dd1a8925c
Revises: a1b2c3d4e5f6
Create Date: 2026-04-06 10:45:49.640391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c0dd1a8925c"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cms_menu",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["cms_menu.id"],
            name=op.f("fk_cms_menu_parent_id_cms_menu"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cms_menu")),
    )
    op.create_table(
        "cms_post",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cms_post")),
        sa.UniqueConstraint("slug", name=op.f("uq_cms_post_slug")),
    )
    op.create_table(
        "cms_menu_post",
        sa.Column("menu_id", sa.String(length=36), nullable=False),
        sa.Column("post_id", sa.String(length=36), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["menu_id"],
            ["cms_menu.id"],
            name=op.f("fk_cms_menu_post_menu_id_cms_menu"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["cms_post.id"],
            name=op.f("fk_cms_menu_post_post_id_cms_post"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("menu_id", "post_id", name=op.f("pk_cms_menu_post")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cms_menu_post")
    op.drop_table("cms_post")
    op.drop_table("cms_menu")
    # ### end Alembic commands ###
