"""add dimension_type_label

Revision ID: 26c712ce07cc
Revises: 9582be3ff65f
Create Date: 2025-11-24 12:18:29.427255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26c712ce07cc"
down_revision = "9582be3ff65f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dimension_type_label",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dimension_type_name", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("given_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dimension_type_name"],
            ["dimension_type.name"],
            name=op.f("fk_dimension_type_label_dimension_type_name_dimension_type"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dimension_type_label")),
    )
    with op.batch_alter_table("dimension_type_label", schema=None) as batch_op:
        batch_op.create_index(
            "idx_dim_type_label_1", ["dimension_type_name"], unique=False
        )
        batch_op.create_index(
            "idx_dim_type_label_2", ["label", "dimension_type_name"], unique=False
        )
        batch_op.create_index(
            "idx_dim_type_label_3", ["given_id", "dimension_type_name"], unique=False
        )

    with op.batch_alter_table("tabular_cell", schema=None) as batch_op:
        batch_op.alter_column(
            "tabular_column_id", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    raise NotImplementedError()
