"""add indices for dim query

Revision ID: 2aa2d4c5c814
Revises: b92d0adae82b
Create Date: 2024-07-24 09:15:16.964601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa2d4c5c814'
down_revision = 'b92d0adae82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension_search_index', schema=None) as batch_op:
        batch_op.create_index('idx_dim_search_index_perf_1', ['value'], unique=False)
        batch_op.create_index('idx_dim_search_index_perf_2', ['type_name', 'value'], unique=False)
        batch_op.create_index('idx_dim_search_index_perf_3', ['dimension_given_id', 'type_name', 'value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension_search_index', schema=None) as batch_op:
        batch_op.drop_index('idx_dim_search_index_perf_3')
        batch_op.drop_index('idx_dim_search_index_perf_2')
        batch_op.drop_index('idx_dim_search_index_perf_1')

    # ### end Alembic commands ###
