"""make dimension type nullable

Revision ID: 3f9fe9c464ef
Revises: a9b7288cb78b
Create Date: 2024-02-06 17:20:39.492657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f9fe9c464ef"
down_revision = "a9b7288cb78b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dimension", schema=None) as batch_op:
        batch_op.alter_column(
            "dataset_dimension_type", existing_type=sa.VARCHAR(), nullable=True
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dimension", schema=None) as batch_op:
        batch_op.alter_column(
            "dataset_dimension_type", existing_type=sa.VARCHAR(), nullable=False
        )
    # ### end Alembic commands ###
