"""add_subtype_to_unique_constraint

Revision ID: 4815dbf75697
Revises: ed0a03d5743b
Create Date: 2026-02-13 14:48:52.116030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4815dbf75697"
down_revision = "ed0a03d5743b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dimension", schema=None) as batch_op:
        batch_op.drop_constraint("_given_id_dataset_id_uc", type_="unique")
        batch_op.create_unique_constraint(
            "_given_id_dataset_id_subtype_uc", ["given_id", "dataset_id", "subtype"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dimension", schema=None) as batch_op:
        batch_op.drop_constraint("_given_id_dataset_id_subtype_uc", type_="unique")
        batch_op.create_unique_constraint(
            "_given_id_dataset_id_uc",
            ["given_id", "dataset_id", "dataset_dimension_type"],
        )

    # ### end Alembic commands ###
