"""add associations tables

Revision ID: 52a899219efc
Revises: 73587e8936b2
Create Date: 2025-01-07 17:05:27.637553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52a899219efc"
down_revision = "73587e8936b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "precomputed_association",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_1_id", sa.String(), nullable=False),
        sa.Column("dataset_2_id", sa.String(), nullable=False),
        sa.Column("axis", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.CheckConstraint(
            "(axis == 'feature') OR (axis == 'sample')", name="ck_assoc_axis"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_1_id"],
            ["dataset.id"],
            name=op.f("fk_precomputed_association_dataset_1_id_dataset"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_2_id"],
            ["dataset.id"],
            name=op.f("fk_precomputed_association_dataset_2_id_dataset"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_precomputed_association")),
        sa.UniqueConstraint(
            "dataset_1_id", "dataset_2_id", "axis", name="assoc_params_uc"
        ),
    )
    with op.batch_alter_table("precomputed_association", schema=None) as batch_op:
        batch_op.create_index("idx_assoc_dataset_1", ["dataset_1_id"], unique=False)
        batch_op.create_index("idx_assoc_dataset_2", ["dataset_2_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("precomputed_association", schema=None) as batch_op:
        batch_op.drop_index("idx_assoc_dataset_2")
        batch_op.drop_index("idx_assoc_dataset_1")

    op.drop_table("precomputed_association")
    # ### end Alembic commands ###
