"""Remove FK constraints for CatalogNode

Revision ID: 71a850e73825
Revises: 8c59f9cc3ef9
Create Date: 2023-02-13 11:46:18.526531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71a850e73825"
down_revision = "8c59f9cc3ef9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catalog_node", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_catalog_node_parent_id_catalog_node", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_catalog_node_dataset_id_dataset", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_catalog_node_dimension_id_dimension", type_="foreignkey"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catalog_node", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_catalog_node_dimension_id_dimension",
            "dimension",
            ["dimension_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_catalog_node_dataset_id_dataset",
            "dataset",
            ["dataset_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            "fk_catalog_node_parent_id_catalog_node",
            "catalog_node",
            ["parent_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###
