"""Add FK constraint naming conventions

Revision ID: 8c59f9cc3ef9
Revises: effce7dff847
Create Date: 2023-02-13 11:37:38.159665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c59f9cc3ef9"
down_revision = "effce7dff847"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_dataset_feature_type_feature_type", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_dataset_sample_type_sample_type", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_dataset_feature_type_feature_type"),
            "feature_type",
            ["feature_type"],
            ["feature_type"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_dataset_sample_type_sample_type"),
            "sample_type",
            ["sample_type"],
            ["sample_type"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("dimension", schema=None) as batch_op:
        batch_op.drop_index("idx_dimension_dataset_id")
        batch_op.create_index(
            "idx_dataset_id_name", ["dataset_id", "name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dimension", schema=None) as batch_op:
        batch_op.drop_index("idx_dataset_id_name")
        batch_op.create_index(
            "idx_dimension_dataset_id", ["dataset_id", "name"], unique=False
        )

    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_dataset_sample_type_sample_type"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_dataset_feature_type_feature_type"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_dataset_sample_type_sample_type",
            "sample_type",
            ["sample_type"],
            ["sample_type"],
        )
        batch_op.create_foreign_key(
            "fk_dataset_feature_type_feature_type",
            "feature_type",
            ["feature_type"],
            ["feature_type"],
        )

    # ### end Alembic commands ###
