"""add column id index

Revision ID: 8d89874406ca
Revises: 020788c82611
Create Date: 2025-04-03 14:30:19.783245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d89874406ca'
down_revision = '020788c82611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabular_cell', schema=None) as batch_op:
        batch_op.create_index('idx_tabular_column_id', ['tabular_column_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabular_cell', schema=None) as batch_op:
        batch_op.drop_index('idx_tabular_column_id')

    # ### end Alembic commands ###
