"""empty message

Revision ID: 8fb30e23d23a
Revises: 2ddb197f8eec
Create Date: 2024-01-04 19:06:53.395917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8fb30e23d23a"
down_revision = "2ddb197f8eec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dimension_search_index",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dimension_id", sa.String(), nullable=False),
        sa.Column("user_supplied_id", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("property", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("type_name", sa.String(), nullable=False),
        sa.Column("type_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["dimension.id"],
            name=op.f("fk_dimension_search_index_dimension_id_dimension"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dimension_search_index")
    # ### end Alembic commands ###
