"""Delete unique constraint for data type and priority

Revision ID: 9d51bb459968
Revises: 2827327b2bd5
Create Date: 2024-06-12 15:29:23.056028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d51bb459968"
down_revision = "2827327b2bd5"
branch_labels = None
depends_on = None


def upgrade():
    # Turn off FK enforcement for this migration since op.batch_alter_table will try to drop the datasets table which has a lot of FKs after making a copy of it (the "PRAGMA foreign_keys" value resets on every DB connection)
    op.execute("PRAGMA foreign_keys = OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.drop_constraint("_data_type_priority_uc", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "_data_type_priority_uc", ["data_type", "priority"]
        )

    # ### end Alembic commands ###
