"""Added PropertyToIndex table

Revision ID: a9b7288cb78b
Revises: f42646e4b96d
Create Date: 2024-01-22 16:06:25.908269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9b7288cb78b"
down_revision = "f2cd9e117188"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "property_to_index",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(), nullable=False),
        sa.Column("property", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
            name=op.f("fk_property_to_index_dataset_id_dataset"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_to_index")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("property_to_index")
    # ### end Alembic commands ###
