"""remove catalog node table

Revision ID: aadda1ee0328
Revises: 2aa2d4c5c814
Create Date: 2024-09-03 15:08:53.162377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aadda1ee0328"
down_revision = "2aa2d4c5c814"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catalog_node", schema=None) as batch_op:
        batch_op.drop_index("idx_catalog_node_dimension_id")
        batch_op.drop_index("idx_dataset_id_dimension_id")

    op.drop_table("catalog_node")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_node",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("dataset_id", sa.VARCHAR(), nullable=True),
        sa.Column("dimension_id", sa.VARCHAR(), nullable=True),
        sa.Column("priority", sa.INTEGER(), nullable=True),
        sa.Column("parent_id", sa.INTEGER(), nullable=True),
        sa.Column("label", sa.VARCHAR(), nullable=False),
        sa.Column("is_continuous", sa.BOOLEAN(), nullable=True),
        sa.Column("is_categorical", sa.BOOLEAN(), nullable=True),
        sa.Column("is_binary", sa.BOOLEAN(), nullable=True),
        sa.Column("is_text", sa.BOOLEAN(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_catalog_node"),
    )
    with op.batch_alter_table("catalog_node", schema=None) as batch_op:
        batch_op.create_index(
            "idx_dataset_id_dimension_id", ["dataset_id", "dimension_id"], unique=False
        )
        batch_op.create_index(
            "idx_catalog_node_dimension_id", ["dimension_id"], unique=False
        )

    # ### end Alembic commands ###
