"""empty message

Revision ID: dfd508572629
Revises: 8fb30e23d23a
Create Date: 2024-01-04 19:13:42.604443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dfd508572629"
down_revision = "8fb30e23d23a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dimension_search_index", schema=None) as batch_op:
        batch_op.alter_column("value", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dimension_search_index", schema=None) as batch_op:
        batch_op.alter_column("value", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
