"""add_release_version_models

Revision ID: e556aa3dabe7
Revises: a1b2c3d4e5f6
Create Date: 2026-04-02 11:26:00.595987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e556aa3dabe7"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add the Virtual Table
    op.execute(
        """
        CREATE VIRTUAL TABLE IF NOT EXISTS release_file_search_index USING fts5(
        file_name,
        file_description,
        file_datatype,
        release_version_name,
        release_name,
        release_version_description,
        release_version_content_hash,
        tokenize='unicode61'
        );
    """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release_version",
        sa.Column("version_name", sa.String(), nullable=False),
        sa.Column("version_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("content_hash", sa.String(length=32), nullable=False),
        sa.Column("release_name", sa.String(), nullable=False),
        sa.Column("citation", sa.String(), nullable=True),
        sa.Column("funding", sa.String(), nullable=True),
        sa.Column("terms", sa.String(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_release_version")),
    )
    with op.batch_alter_table("release_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_release_version_content_hash"),
            ["content_hash"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_release_version_release_name"),
            ["release_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_release_version_version_name"),
            ["version_name"],
            unique=False,
        )

    op.create_table(
        "release_file",
        sa.Column("release_version_id", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("datatype", sa.String(), nullable=False),
        sa.Column("size", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("bucket_url", sa.String(), nullable=True),
        sa.Column("taiga_id", sa.String(), nullable=True),
        sa.Column("canonical_taiga_id", sa.String(), nullable=True),
        sa.Column("md5_hash", sa.String(length=32), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("pipeline_name", sa.String(), nullable=True),
        sa.Column("is_main_file", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_version_id"],
            ["release_version.id"],
            name=op.f("fk_release_file_release_version_id_release_version"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_release_file")),
    )
    with op.batch_alter_table("release_file", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_release_file_file_name"), ["file_name"], unique=False
        )

    op.create_table(
        "release_pipeline",
        sa.Column("release_version_id", sa.String(), nullable=False),
        sa.Column("pipeline_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_version_id"],
            ["release_version.id"],
            name=op.f("fk_release_pipeline_release_version_id_release_version"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_release_pipeline")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release_pipeline")
    with op.batch_alter_table("release_file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_release_file_file_name"))

    op.drop_table("release_file")
    with op.batch_alter_table("release_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_release_version_version_name"))
        batch_op.drop_index(batch_op.f("ix_release_version_release_name"))
        batch_op.drop_index(batch_op.f("ix_release_version_content_hash"))

    op.drop_table("release_version")
    # ### end Alembic commands ###
    op.execute("DROP TABLE IF EXISTS release_file_search_index")
