"""add predictive models tables

Revision ID: eb9295846cb3
Revises: ed0a03d5743b
Create Date: 2026-02-18 14:58:38.625807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb9295846cb3"
down_revision = "ed0a03d5743b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "predictive_model_config",
        sa.Column("dimension_type_name", sa.String(), nullable=False),
        sa.Column("model_config_name", sa.String(), nullable=False),
        sa.Column("model_config_description", sa.String(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["dimension_type_name"],
            ["dimension_type.name"],
            name=op.f("fk_predictive_model_config_dimension_type_name_dimension_type"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictive_model_config")),
        sa.UniqueConstraint(
            "dimension_type_name",
            "model_config_name",
            name="uq_predictive_model_config_dim_type_name",
        ),
    )
    op.create_table(
        "predictive_model_result",
        sa.Column("config_id", sa.String(length=36), nullable=False),
        sa.Column("actuals_dataset_id", sa.String(), nullable=False),
        sa.Column("predictions_dataset_id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["actuals_dataset_id"],
            ["dataset.id"],
            name=op.f("fk_predictive_model_result_actuals_dataset_id_dataset"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["predictive_model_config.id"],
            name=op.f("fk_predictive_model_result_config_id_predictive_model_config"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["predictions_dataset_id"],
            ["dataset.id"],
            name=op.f("fk_predictive_model_result_predictions_dataset_id_dataset"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictive_model_result")),
        sa.UniqueConstraint(
            "config_id",
            "actuals_dataset_id",
            "predictions_dataset_id",
            name="uq_predictive_model_result_config_datasets",
        ),
    )
    with op.batch_alter_table("predictive_model_result", schema=None) as batch_op:
        batch_op.create_index(
            "idx_predictive_model_result_actuals_dataset_id",
            ["actuals_dataset_id"],
            unique=False,
        )
        batch_op.create_index(
            "idx_predictive_model_result_config_id", ["config_id"], unique=False
        )
        batch_op.create_index(
            "idx_predictive_model_result_predictions_dataset_id",
            ["predictions_dataset_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("predictive_model_result", schema=None) as batch_op:
        batch_op.drop_index("idx_predictive_model_result_predictions_dataset_id")
        batch_op.drop_index("idx_predictive_model_result_config_id")
        batch_op.drop_index("idx_predictive_model_result_actuals_dataset_id")

    op.drop_table("predictive_model_result")
    op.drop_table("predictive_model_config")
    # ### end Alembic commands ###
