"""remove_cascade_delete_from_dimension_type_fks

Revision ID: ed0a03d5743b
Revises: 020788c82611
Create Date: 2026-02-05 08:42:02.758756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0a03d5743b'
down_revision = '020788c82611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matrix_dataset', schema=None) as batch_op:
        batch_op.drop_constraint('fk_matrix_dataset_feature_type_name_dimension_type', type_='foreignkey')
        batch_op.drop_constraint('fk_matrix_dataset_sample_type_name_dimension_type', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_matrix_dataset_feature_type_name_dimension_type'), 'dimension_type', ['feature_type_name'], ['name'])
        batch_op.create_foreign_key(batch_op.f('fk_matrix_dataset_sample_type_name_dimension_type'), 'dimension_type', ['sample_type_name'], ['name'])

    with op.batch_alter_table('tabular_dataset', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tabular_dataset_index_type_name_dimension_type', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tabular_dataset_index_type_name_dimension_type'), 'dimension_type', ['index_type_name'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabular_dataset', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tabular_dataset_index_type_name_dimension_type'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tabular_dataset_index_type_name_dimension_type', 'dimension_type', ['index_type_name'], ['name'], ondelete='CASCADE')

    with op.batch_alter_table('matrix_dataset', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_matrix_dataset_sample_type_name_dimension_type'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_matrix_dataset_feature_type_name_dimension_type'), type_='foreignkey')
        batch_op.create_foreign_key('fk_matrix_dataset_sample_type_name_dimension_type', 'dimension_type', ['sample_type_name'], ['name'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_matrix_dataset_feature_type_name_dimension_type', 'dimension_type', ['feature_type_name'], ['name'], ondelete='CASCADE')

    # ### end Alembic commands ###
