"""Rename dimension search index columns

Revision ID: f47b426e0e95
Revises: 8170070a55ca
Create Date: 2024-01-18 15:37:38.800800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f47b426e0e95"
down_revision = "8170070a55ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dimension_search_index", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("dimension_given_id", sa.String(), nullable=False)
        )
        batch_op.add_column(sa.Column("axis", sa.String(), nullable=False))
        batch_op.drop_column("user_supplied_id")
        batch_op.drop_column("type_type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dimension_search_index", schema=None) as batch_op:
        batch_op.add_column(sa.Column("type_type", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("user_supplied_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_column("axis")
        batch_op.drop_column("dimension_given_id")

    # ### end Alembic commands ###
