#!/usr/bin/env bash
source setup_env.sh

# If you want to use the DevConfig (that is the
# configuration which matches the dev database)
# for local testing but you want to see a different
# theme and set of downloadable files, set the variable below. If not set, defaults to the public
# theme.

#export DEPMAP_THEME=dmc

# If you want to run locally using a copy of a production
# or staging database. Uncomment and set the below accordingly.

#export DEPMAP_ENV=istaging
#export CONFIG_PATH=../config/dmc/settings.py
#export DEPMAP_OVERRIDES=./overrides.py

if [[ "$1" == "run" ]] ; then
  shift
  exec flask run --without-threads "$@"
else
  exec flask "$@"
fi
