---
name: Build breadbox

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  publish-breadbox-client:
    if: ${{ (github.ref_name == 'master') }}
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0
        # pulls latest changes from head
      - run: |
          git pull origin HEAD:master
      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.DEPMAP_ARTIFACTS_SVC_ACCT }}"

      - name: Prepare breadbox client
        uses: ./.github/actions/prepare-breadbox-client # checks out and generates breadbox client code

      - name: Check that the breadbox client passes pyright
        working-directory: ./breadbox-client
        run: "poetry install && poetry run pyright breadbox_facade"

      - name: Publish breadbox client
        uses: ./.github/actions/publish-breadbox-client
