name: Build and push pipeline-tda image

on:
  push:
    branches:
      - "master"
    paths:
      - "pipeline/build-pipeline-docker-images/tda-docker/**"
      - "pipeline/build-pipeline-docker-images/build.sh"
      - ".github/workflows/build_tda_docker.yml"

env:
  ARTIFACT_REGISTRY_REPO: us-central1-docker.pkg.dev/depmap-consortium/depmap-docker-images/depmap-pipeline-tda
  DOCKER_TAG: ga2-build-${{ github.run_number }}
  DOCKERFILE_DIR: tda-docker

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Login to Artifact Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.DEPMAP_DEPLOY_SVC_ACCT }}
      - name: Build and push depmap pipeline tda docker image
        run: cd pipeline/build-pipeline-docker-images && bash build.sh ${{ env.ARTIFACT_REGISTRY_REPO }} ${{ env.DOCKER_TAG }} ${{ env.DOCKERFILE_DIR}}
