---
name: Publish breadbox client

on:
  workflow_dispatch:

jobs:
  publish-breadbox-client:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0

      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.DEPMAP_ARTIFACTS_SVC_ACCT }}"

      - name: Prepare breadbox client
        uses: ./.github/actions/prepare-breadbox-client # checks out and generates breadbox client code

      - name: Publish breadbox client
        uses: ./.github/actions/publish-breadbox-client
